# Generated by Django 4.2.1 on 2023-05-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/images')),
                ('address', models.CharField(max_length=200)),
                ('isFavorite', models.BooleanField(default=False)),
            ],
        ),
    ]
